_target_: leffa.models.simple_vton_model.SimpleVtonModel
pretrained_model_name_or_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-xl-1.0-inpainting-0.1
pretrained_vae_name_or_path: manifold://genads_models/tree/zijianzhou/model/FLUX.1-dev/vae
pretrained_garmentnet_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-xl-base-1.0
new_in_channels: 36
height: ${constants.height}
width: ${constants.width}
garment_dropout_ratio: 0.1
use_dream: false
dream_detail_preservation: 10.0
skip_cross_attention: true
skip_cross_attention_garmentnet: true
copy_unet_to_unet_encoder: false
only_optimize_unet_attn1: false
optimize_unet: true
optimize_unet_encoder: true
use_pixel_space_supervision: false
pixel_space_supervision_lambda: 10.0
